### ISSUE TITLE
Not compiling on nightly v1.53

### ISSUE THREAD

**Issue by minghuaw** [RusPiRo/ruspiro-tutorials#11]
What is the latest nightly rust version that is supported? Currently the template cannot even compile with nightly v1.53

**Comment by 2ndTaleStudio** [comment]
Hi,

thanks for raising the issue. The tutorials should compile fine at least up to nightly-2021-01-30.

Unfortunately I seem to have introduced a regression with some dependent crate (`ruspiro-interrupt-macros`) which leads to a failing build. I'll try to fix this as soon as possible.

Best regards.

**Comment by 2ndTaleStudio** [comment]
Additional Update:
I yanked the erroneous version of `ruspiro-interrupt-macros` that caused the regression in crates.io.

So you might want to run `cargo update` which will update the  dependencies for the actual tutorial/template you are about to build followed by the `cargo +nightly-2021-01-30 make pi3 --profile a64` assuming you have installed the respective nightly version.

Hope this solves your issues. I'll keep working on an update to get the tutorials compiled with latest nightly version.
