### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by chemicstry** [RusPiRo/ruspiro-tutorials#12]
Hi!

First of all, I have to say that this is an amazing project and the amount of stuff that you already got working is incredible!

My original interest was to implement bare-metal RTIC on RPi4 so I firstly experimented with [rust-raspberrypi-OS-tutorials](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials) to get familliar with the hardware. However, that project didn't really suit my needs as it is a single-crate monolithic kernel and I wanted something similar to the reusable cortex-m ecosystem. So I started splitting the kernel into separate crates until I found this project. Luckily, I didn't get far yet :D 

The first question that worries me the most is the isolation from the rest of the embedded rust ecosystem. I think there is a lot of potential here for cooperation:
- Crates like `ruspiro-locks`, `ruspiro-singleton`, `ruspiro-mmu`, and maybe more could be useful for other cortex-a based chips and maybe could be combined into `cortex-a-rt` crate similar to `cortex-m-rt`. This is mostly about the naming and discoverability, as it is now solely targeted at RPi3.
- Similarly crates like `ruspiro-uart`, `ruspiro-gpio` could become `primecell-hal` (for the PrimeCell UART) and `bcm-hal` (for broadcom GPIO and mini UART). Currently they have hardcoded RPi3 memory locations and cannot be reused outside this project. They could instead be initialized with `new(periph_base: *usize)` and concrete peripheral base addresses would be provided by `raspberry-hal` and similar chip crates.
- I may not know all details, but it seems that a lot of crates reimplement what already exists: `ruspiro-console` instead of `log` or `tracing`, `ruspiro-channel` instead of `heapless` or `futures-intrusive`, `ruspiro-brain` instead of `async_task`, etc.

I think integrating with rust ecosystem would be beneficial both ways as it would attract developers to this project and would provide many useful crates for everyone. I am personally interested in this and would gladly contribute. Let me know what you think.

**Comment by 2ndTaleStudio** [comment]
Hi,

first of all thanks for your kind words.

Well, regarding your question the answer is kind of simply put: It all started as a personal project with lots of experimentation around Rust as language and the ecosystem as such and how it may fit my personal aspirations in building a small OS for the Raspberry Pi. The project was also dedicated to provide a great playground for my own learning experience around several aspects of micro controller / OS development as well as the different Rust language features. Back than while starting the project there was not much available for `no_std` thus I mainly decided to build the small parts that just fits my personal needs from scratch without bothering the ecosystem with my rooky Rust knowledge at the beginning.

However, I've never thought along the road that there might be the possibility to re-integrate the growing and more sophisticated crates into the whole embedded/micro controller Rust ecosystem. So thanks for bringing this up. I may take some efforts to see how my implementations might fit into the embedded ecosystems but there might be no timeline planned soon. I do remember having investigated some HAL crates for GPIO and the like but did not found them straight forward to use for my use cases. But things might have changed and could require some re-evaluation.

At the moment I'm kind of in the middle of some re-factoring of the majority of crates and also adjusting the tutorials reflecting those changes. Once done it might be the time to re-think the integration into the whole Rust ecosystem and any contribution at this step would be much appreciated.

However, the structure and implementation details of the crates are kind of evolving around the ultimate goal to write a specific new OS for the Raspberry Pi so it might be still questionable whether this would be of any benefit for re-use in the broader sense.

What I'm trying to say: There are no concrete plans for a general integration into the eco-system, but if you have ideas for different crates how they could evolve to be closer to the ecosystem and/or easier to consume for non-Raspberry Pi targets feel encouraged to raise issues or PR's for the respective crates.

**Comment by chemicstry** [comment]
Thank you for the explanation, that makes sense.

I will look around and see if I can reuse something without too much changes and maybe open a PR.
