### ISSUE TITLE
error: the legacy LLVM-style asm! syntax is no longer supported

### ISSUE THREAD

**Issue by bitkis** [RusPiRo/ruspiro-tutorials#8]
Hey there!

It seems a recent rust nightly build introduced the new asm! syntax specified in RFC 2873. Also, I believe, there are a couple of other similar issues. Questions therefore:

1. Do you accept external PRs?
2. Since I could not find mention of a particular nightly build suggested in the tutorial, I lean towards making the fixes unconditional. Agree?

Great project, btw :)
--Boris

**Comment by bitkis** [comment]
After looking at it a bit more, I propose at this point switching from `asm!` to `llvm_asm!`. After new `asm!` syntax will stabilize, yet another fix will be needed.

**Comment by 2ndTaleStudio** [comment]
Hi,
thanks for your hints. I've also thought a good point in time to change the `asm!` to `llvm_asm!` macros :)

I'd appreciate your contribution. And you are right, there is no direct nightly version I was constraining the project to.

Feel free to submit a PR.

Thanks in advance.
BR
André

**Comment by bitkis** [comment]
It looks like there is a dependency issue in CI. Of course we can process the PRs one-by-one, rerunning CI. But have you ever considered moving all crates into one repo?

**Comment by 2ndTaleStudio** [comment]
Hey, well I have this ["mono-repo"](https://github.com/RusPiRo/ruspiro) that refers to the different individual repos as sub-modules but this might also not being much of a help here. I might need to reconsider a proper CI setup useful for PR validation. Putting all crates originally into one bug repo gives the downsize that it is not suited for independent maintenance, issue tracking and the like. I'll review this based on your PR's and might be able to come up with a better CI config ;)

Thanks for your efforts and the PR's created.

**Comment by bitkis** [comment]
Actually, there should be some version bumping done here and there. If you don't catch it now I'll make yet another PR.

Also, I have few questions regarding the project in general. Should I ask them here, open a new issue or over email?

**Comment by 2ndTaleStudio** [comment]
Hey, yea I'm actually going through the PR's updating the version and preparing publishing to crates.io and also try to figure a better travis-CI pipeline :)

Feel free to open a new issue to discuss further topic if you don't mind and the questions and their answers might also be of interest for others ;)

Otherwise email is also fine.

**Comment by bitkis** [comment]
Hey,

Be sure to bump versions for dependences -- in some crates they were outdated and that caused problems with tutorial builds

**Comment by 2ndTaleStudio** [comment]
Thx for the hint ;)
